#!/bin/sh
cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
[ ! -e "$cachedir" ] && mkdir -p "$cachedir"
cache="$cachedir/dmenu_run"


IFS=:
if stest -dqr -n "$cache" $PATH; then
	stest -flx $PATH | sort -u | tee "$cache"
else
	cat "$cache"
fi
